#!/bin/bash

useValgrind=false
while getopts v flag
do
	case "${flag}" in
		v) useValgrind=true;;
	esac
done

echo "=================="
echo "Running Long Tests"
for t in {1..18}
do
	echo ----------------
	echo Running Test $t
	if ($useValgrind)
	then
		valgrind -q ./longtest -h $t
	else
		./longtest -h $t
	fi
done

echo "===================="
echo "Running String Tests"
for t in {1..18}
do
	echo ----------------
	echo Running Test $t
	if ($useValgrind)
	then
		valgrind -q ./stringtest -h $t
	else
		./stringtest -h $t
	fi
done
